'use client'

/**
 * ScenarioPanel — Vercel tab-ghost row.
 *
 * Centered row of pill-sm (64 px radius) ghost pills.
 * Active pill polarity-flipped to ink-primary (the brand's single CTA tone).
 * No emoji — clean type, per the brand voice.
 */

import type { Scenario } from '../types'
import { SCENARIOS } from '../scenarios'
import { useI18n } from '../context/I18nContext'

interface ScenarioPanelProps {
  activeScenario: Scenario | null
  onSelect: (scenario: Scenario | null) => void
}

export default function ScenarioPanel({ activeScenario, onSelect }: ScenarioPanelProps) {
  const { t } = useI18n()

  return (
    <div className="shrink-0 bg-canvas hairline shadow-card-md">
      <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between gap-4">

        {/* Mono eyebrow on the left — the "technical layer" voice */}
        <span className="eyebrow hidden md:inline shrink-0 bg-canvas-soft border border-hairline rounded-md px-2.5 py-1.5">
          {t('scenario.header')}
        </span>

        {/* Centered pill row */}
        <div className="flex items-center gap-1 bg-canvas-soft-2 rounded-full px-1 py-1 overflow-x-auto no-scrollbar">
          {/* Default-view pill */}
          <button
            onClick={() => onSelect(null)}
            className={`
              h-8 px-4 rounded-full text-[13px] font-medium tracking-body-sm
              transition-all whitespace-nowrap
              ${activeScenario === null
                ? 'bg-canvas text-ink shadow-card'
                : 'bg-transparent text-body hover:text-ink hover:bg-canvas'}
            `}
          >
            {t('scenario.none.label')}
          </button>

          {/* Hairline separator */}
          <span className="w-px h-5 bg-hairline mx-1 shrink-0" />

          {SCENARIOS.map(scenario => {
            const isActive = activeScenario?.id === scenario.id
            return (
              <button
                key={scenario.id}
                onClick={() => onSelect(isActive ? null : scenario)}
                title={t(scenario.description_key)}
                className={`
                  h-8 px-4 rounded-full text-[13px] font-medium tracking-body-sm
                  inline-flex items-center gap-2 transition-all whitespace-nowrap
                  ${isActive
                    ? 'bg-canvas text-ink shadow-card'
                    : 'bg-transparent text-body hover:text-ink hover:bg-canvas'}
                `}
              >
                <span>{t(scenario.label_key)}</span>
                <span className="font-mono text-[10px] tracking-[0.05em] text-mute">
                  {scenario.horizon_year}
                </span>
              </button>
            )
          })}

          {/* AI Goal — only shown when the active scenario was generated by the LLM */}
          {activeScenario?.id === 'custom' && activeScenario.custom_label && (
            <>
              <span className="w-px h-5 bg-hairline mx-1 shrink-0" />
              <span className="eyebrow px-2 shrink-0 text-mute">AI</span>
              <button
                onClick={() => onSelect(null)}
                title="Clear AI goal"
                className="
                  h-8 px-4 rounded-full text-[13px] font-medium tracking-body-sm
                  inline-flex items-center gap-2 transition-all whitespace-nowrap
                  bg-canvas text-link shadow-card border border-link/20
                "
              >
                <span className="w-1.5 h-1.5 rounded-full bg-link shrink-0" />
                <span>{activeScenario.custom_label}</span>
                <span className="font-mono text-[10px] tracking-[0.05em] text-mute">
                  {activeScenario.horizon_year}
                </span>
              </button>
            </>
          )}
        </div>

        {/* Right-side state chip */}
        <div className={`
          eyebrow hidden md:inline-flex items-center gap-1.5 shrink-0
          px-2.5 py-1 rounded-full border transition-colors
          ${activeScenario
            ? 'bg-canvas border-hairline-strong text-link'
            : 'bg-canvas-soft border-hairline text-mute'}
        `}>
          <span className={`w-1.5 h-1.5 rounded-full transition-colors ${activeScenario ? 'bg-link' : 'bg-hairline-strong'}`} />
          {activeScenario ? t('scenario.status.active') : t('scenario.none.label')}
        </div>
      </div>
    </div>
  )
}
