/**
 * Pre-defined planning scenarios for the HK District Viability map.
 *
 * Stage 1 — AHP-derived weights (all CR < 0.07).
 * Generated by: uv run python weights_ahp.py
 * Land-use fractions in districts.geojson are real raster_2024 values
 * produced by: uv run python build_data.py
 *
 * Contract: imports only from '../types' (shared contract file).
 * Do not edit without coordinating with Agent B.
 */

import type { Scenario } from './types';

// ---------------------------------------------------------------------------
// Stage-1 AHP-derived weight sets  (CR < 0.07 for all scenarios)
//
// Generated by: uv run python weights_ahp.py
// Weights express relative importance; scoring.ts normalises them to sum = 1
// internally, so absolute magnitudes don't matter — only ratios do.
// ---------------------------------------------------------------------------

/** Green HK 2050 — headroom + area dominant (AHP CR = 0.0199). */
const greenHk2050: Scenario = {
  id:              'green_hk_2050',
  target:          'green',
  weights: {
    displacement: 0.1377,
    age:          0.1099,
    headroom:     0.4191,
    area:         0.3333,
  },
  label_key:       'scenario.green_hk_2050.label',
  description_key: 'scenario.green_hk_2050.description',
  horizon_year:    2050,
};

/** Industrial Growth — area + headroom dominant (AHP CR = 0.0665). */
const industrialGrowth: Scenario = {
  id:              'industrial_growth',
  target:          'industrial',
  weights: {
    displacement: 0.1963,
    age:          0.1185,
    headroom:     0.2926,
    area:         0.3926,
  },
  label_key:       'scenario.industrial_growth.label',
  description_key: 'scenario.industrial_growth.description',
  horizon_year:    2040,
};

/** Education Hub — headroom dominant (AHP CR = 0.0206). */
const educationHub: Scenario = {
  id:              'education_hub',
  target:          'educational',
  weights: {
    displacement: 0.1293,
    age:          0.098,
    headroom:     0.6009,
    area:         0.1719,
  },
  label_key:       'scenario.education_hub.label',
  description_key: 'scenario.education_hub.description',
  horizon_year:    2035,
};

/**
 * Urban Renewal — 5-term weights (AHP CR = 0.0225 for base 4 terms;
 * renewal term added at 0.20 and others scaled by 0.80).
 * ageing_building_share is now present on all 18 districts (build_data.py),
 * so the renewal term in scoring.ts is active.
 */
const urbanRenewal: Scenario = {
  id:              'urban_renewal',
  target:          'residential',
  weights: {
    displacement: 0.1638,
    age:          0.2305,
    headroom:     0.2705,
    area:         0.1352,
    renewal:      0.20,
  },
  label_key:       'scenario.urban_renewal.label',
  description_key: 'scenario.urban_renewal.description',
  horizon_year:    2040,
};

/** All four scenarios in display order. */
export const SCENARIOS: Scenario[] = [
  greenHk2050,
  industrialGrowth,
  educationHub,
  urbanRenewal,
];

/** Look up a scenario by id (throws if not found). */
export function getScenario(id: string): Scenario {
  const s = SCENARIOS.find(s => s.id === id);
  if (!s) throw new Error(`Unknown scenario id: ${id}`);
  return s;
}
